name: Automerge PRs

on:
  pull_request:
    types: [labeled, review_requested, review_request_removed, review]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label is AUTOMERGE and 1 approvals
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const label = "AUTOMERGE";
            const requiredApprovals = 2;
            const pr = context.payload.pull_request;
            
            if (pr.labels.find(l => l.name === label)) {
              console.log(`PR #${pr.number} has the label ${label}`);
              
              const approvals = await github.pulls.listReviews({
                owner: pr.base.repo.owner.login,
                repo: pr.base.repo.name,
                pull_number: pr.number,
              });
              
              const approvedReviews = approvals.data.filter(review => review.state === 'APPROVED');
              if (approvedReviews.length >= requiredApprovals) {
                console.log(`PR #${pr.number} has ${approvedReviews.length} approvals. Ready to SQUASH MERGE!`);
                
                // Realizar SQUASH MERGE
                - name: Checkout PR branch
                  uses: actions/checkout@v2
                  with:
                    ref: ${{ github.head_ref }}
                - name: Merge and squash PR
                  run: |
                    git checkout ${{ github.base_ref }}
                    git merge --squash ${{ github.head_ref }}
                    git commit -m "Squash merge PR #${{ github.event.number }}"
                    git push origin ${{ github.base_ref }}
              } else {
                console.log(`PR #${pr.number} needs ${requiredApprovals - approvedReviews.length} more approvals.`);
              }
            }
